#!/bin/bash
# This script has been tested with the following operating systems:
#
# 1. Ubuntu 18.04

set -e

readonly DOWNLOAD_CLOUDWATCH_PACKAGE_PATH="/tmp/amazon-cloudwatch-agent.deb"
readonly CLOUDWATCH_CONFIGURATION_PATH="/opt/aws/aws-cloudwatch-agent/config/cloudwatch-config.json"

readonly SCRIPT_NAME="$(basename "$0")"

function log {
  local -r level="$1"
  local -r message="$2"
  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info {
  local -r message="$1"
  log "INFO" "$message"
}

function log_warn {
  local -r message="$1"
  log "WARN" "$message"
}

function log_error {
  local -r message="$1"
  log "ERROR" "$message"
}

# A retry function that attempts to run a command a number of times and returns the output
function retry {
  local -r cmd="$1"
  local -r description="$2"

  for i in $(seq 1 5); do
    log_info "$description"

    # The boolean operations with the exit status are there to temporarily circumvent the "set -e" at the
    # beginning of this script which exits the script immediatelly for error status while not losing the exit status code
    output=$(eval "$cmd") && exit_status=0 || exit_status=$?
    log_info "$output"
    if [[ $exit_status -eq 0 ]]; then
      echo "$output"
      return
    fi
    log_warn "$description failed. Will sleep for 10 seconds and try again."
    sleep 10
  done;

  log_error "$description failed after 5 attempts."
  exit $exit_status
}

function install_dependencies {
  log_info "Installing dependencies"

  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl fail2ban
}

function fetch_cloudwatch_pkg {
  local -r version="$1"
  local download_url="$2"

  if [[ -z "$download_url" && -n "$version" ]]; then
    download_url="https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/${version}/amazon-cloudwatch-agent.deb"
  fi

  retry \
    "curl -o '$DOWNLOAD_CLOUDWATCH_PACKAGE_PATH' '$download_url' --location --silent --fail --show-error" \
    "Downloading CloudWatch agent to $DOWNLOAD_CLOUDWATCH_PACKAGE_PATH"
}

function install_cloudwatch_agent {
  log_info "Installing CloudWatch agent"

  sudo dpkg -i -E $DOWNLOAD_CLOUDWATCH_PACKAGE_PATH

  sudo mkdir -p $CLOUDWATCH_CONFIGURATION_PATH
  sudo mv "/tmp/cloudwatch-config.json" $CLOUDWATCH_CONFIGURATION_PATH
  sudo chmod +x $CLOUDWATCH_CONFIGURATION_PATH
}

function install {
  local version="latest"
  local download_url=""

  log_info "Staring setup"

  install_dependencies
  fetch_cloudwatch_pkg "$version" "$download_url"
  install_cloudwatch_agent
}

install "$@"
